name: "gskriptor"
title: "gskriptor"
description: "My tech art blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
disqus: ''
include: ["_pages"]
permalink: /:title/
show_downloads: true
google_analytics: ''
mailchimp-list: ''
theme: jekyll-theme-slate
